config/routes.rb
Ctvdn::Application.routes.draw do

  resources :channels

  resources :packages

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  
  resources :subscribers do
    resources :payments
    collection do
      get 'inactive'
      get 'active'
    end
  end
  
  resources :payments do
    collection do
      get 'overdues'
    end
  end

  root :to => 'admin#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :name, :price
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.paginate(:page  => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel: <%=@channel.name%></h1>

<%= render 'form' %>

<%= link_to 'Show', @channel, class: 'action show' %> |
<%= link_to 'List all channels', channels_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || channels_path, class: 'action back' %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <tr class="header">
    <th>Name</th>
    <th>Price</th>
    <th colspan="3">Tasks</th>
  </tr>

<% @channels.each_with_index do |channel,i| %>
  <tr class="<%= i%2 == 0 ? '':'alternate'%>">
    <td><%= channel.name %></td>
    <td><%= channel.price %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: 'View'), channel, class: 'icon', title: 'view') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/pen-128.png'), alt: 'Edit'), edit_channel_path(channel), {class: 'icon', title: 'edit'}) if current_user && current_user.has_role?(User::CHANNELS + User::CAN_EDIT)%></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/trash-128.png'), alt: 'Delete'), channel, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon', title:  'delete') if current_user && current_user.has_role?(User::CHANNELS + User::CAN_DESTROY)%></td>
    
  </tr>
<% end %>
</table>
<%= will_paginate @packages %>
<br />

<%= link_to 'Add new channel', new_channel_path, class: 'action add-new' %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', request.referer || channels_path, class: 'action back' %>

app/views/channels/show.html.erb
<% unless notice.blank?%>
	<p id="notice"><%= notice %></p> 
<% end %>

<p>
  <b>Name:</b>
  <%= @channel.name %>
</p>

<p>
  <b>Price:</b>
  <%= @channel.price %>
</p>


<%= link_to 'Edit', edit_channel_path(@channel), class: 'action edit' %> |
<%= link_to 'List all channels', channels_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || channels_path, class: 'action back' %>