config/routes.rb
Ctvdn::Application.routes.draw do

  resources :channels

  resources :packages

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  
  resources :subscribers do
    resources :payments
    collection do
      get 'inactive'
      get 'active'
    end
  end
  
  resources :payments do
    collection do
      get 'overdues'
    end
  end

  root :to => 'admin#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :amount, :subscriber_id, :payment_id, :payment_ref, :agent_id, :created_by, :updated_by, :collected_on, :for_cycle
  belongs_to :subscriber
  belongs_to :agent, class_name: User
  
  
  def self.all_payments_of_subscriber(subscriber)
    payments = Payment.where(:subscriber_id => subscriber.id).order('id DESC')
    return payments
  end
  
  def self.get_overdue_list
    overdues = []
    Subscriber.where(:status => true).each do |s|
      p = s.payments.last
      if p.nil?
        overdues.push({s: s, p: nil})
      else
        overdues.push({s: s, p: p}) if s.cycle_starts_on < Date.today.day && p.for_cycle + 30.days < Date.today
      end
    end
    return overdues
  end
  
  def self.generate_payment_ref
    ref = ""
    ref = "#{ref}d#{Time.now.strftime("%Y%m%d")}"
    ref = "#{ref}i#{Payment.last.id.to_i+1}"
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index
    @subscriber = Subscriber.find_by_id(params[:subscriber_id])
    if @subscriber
      @payments = Payment.paginate(:page  => params[:page], :per_page => 20).where(subscriber_id: @subscriber.id).order('id DESC')
      @list_name = "all payments for subscriber: #{@subscriber.id} (#{@subscriber.name})"
    else
      @payments = Payment.paginate(:page  => params[:page], :per_page => 20).order('id DESC')
      @list_name = "all payments"
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    subscriber = Subscriber.find_by_id(params[:subscriber_id])
    @payment = Payment.new
   
    if subscriber
      @header_sfx = " for subscriber: #{subscriber.id} (#{subscriber.name})"
      @payment.subscriber_id = subscriber.id 
      @payment.amount = subscriber.subscription_amount
    end
    @payment.agent_id = current_user.id if current_user && current_user.has_role?(User::IS_AN_AGENT)
        
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
  
  def overdues
    @overdues = Payment.get_overdue_list
    respond_to do |format|
      format.html # overdues.html.erb
      format.json { render json: @overdues }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_ref %>
    <%= f.text_field :payment_ref, value: @payment.payment_ref||Payment.generate_payment_ref%>
  </div>
  <div class="field">
    <%= f.label :subscriber_id %>
    <%= f.select(:subscriber_id, options_for_select(Subscriber.all.collect{|s| ["#{s.id} : #{s.name}", s.id]}, [@payment.subscriber_id]), {prompt: 'Select subscriber'})%>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :for_cycle %>
    <%= f.date_select :for_cycle, discard_day: true %>
  </div>
  <div class="field">
    <%= f.label :agent_id %>
    <%= f.select(:agent_id, User.all_agents.collect{|a| [a.name, a.id]}, {prompt: 'Select agent'})%>
  </div>
  <div class="field">
    <%= f.label :collected_on, {:class => 'collected-on'} %>
    <%= f.date_select :collected_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment: <%=@payment.id%></h1>

<%= render 'form' %>

<%= link_to 'Show', @payment, class: 'action show' %> |
<%= link_to 'List all payments', payments_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || payments_path, class: 'action back' %>

app/views/payments/index.html.erb
<h1>Listing <%= @list_name %></h1>

<table>
  <tr class="header">
    <th>Payment Id</th>
    <th>Payment Ref</th>
    <th>Subscriber Id</th>
    <th>Subscriber Name</th>
    <th>Smartcard Number</th>
    <th>Amount</th>
    <th>For Period</th>
    <th>Collected By</th>
    <th>Collected On</th>
    <th colspan="3">Tasks</th>
  </tr>

<% @payments.each_with_index do |payment,i| %>
  <tr class="<%= i%2 == 0 ? '':'alternate'%>">
    <td><%= payment.id %></td>
    <td><%= payment.payment_ref %></td>
    <td><%= payment.subscriber_id %></td>
    <td>
    	<%= payment.subscriber.name %>
    	<%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: "View subscriber's details"), payment.subscriber, class: 'icon', title: "View this subscriber's details") %>
	</td>
    <td><%= payment.subscriber.smartcard_number %></td>
    <td><%= payment.amount %></td>
    <td><%= payment.for_cycle.strftime("%m/%Y") %></td>
    <td><%= payment.agent.name %></td>
    <td><%= payment.collected_on %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: 'View'), payment, class: 'icon', title: 'view') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/pen-128.png'), alt: 'Edit'), edit_payment_path(payment), {class: 'icon', title: 'edit'}) if current_user && current_user.has_role?(User::PAYMENTS + User::CAN_EDIT)%></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/trash-128.png'), alt: 'Delete'), payment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon', title:  'delete') if current_user && current_user.has_role?(User::PAYMENTS + User::CAN_DESTROY)%></td>
  </tr>
<% end %>
</table>
<%= will_paginate @payments %>
<br />

<%= link_to @subscriber.nil? ? 'Add new payment' : 'Add new payment for this subscriber', @subscriber.nil? ? new_payment_path : new_subscriber_payment_path(@subscriber), class: 'action add-new'  %>

app/views/payments/new.html.erb
<h1>New payment<%=@header_sfx%></h1>

<%= render 'form' %>

<%= link_to 'Back', request.referer || payments_path, class: 'action back' %>

app/views/payments/overdues.html.erb
<h1>Overdue payments</h1>

<table>
  <tr class="header">
	<th rowspan="2">Subscriber Id</th>
    <th rowspan="2">Subscriber Name</th>
    <th rowspan="2">Smartcard Number</th>
    <th colspan="6">Last Payment Details</th>
    <th colspan="5" rowspan="2">Tasks</th>
  </tr>
  <tr class="header">
    <th>Payment Id</th>
    <th>Payment Ref</th>
    <th>Amount</th>
    <th>For Period</th>
    <th>Collected By</th>
    <th>Collected On</th>
  </tr>

<% @overdues.each_with_index do |overdues, i| %>
  <%
    subscriber = overdues[:s]
    payment    = overdues[:p]
  %>  
  <tr class="<%= i%2 == 0 ? '':'alternate'%>">
    <td><%= subscriber.id %></td>
    <td>
    	<%= subscriber.name%>
    	<%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: "View subscriber's details"), subscriber, class: 'icon', title: "View this subscriber's details") %>
    </td>
    <td><%= subscriber.smartcard_number %></td>
    <% if payment %>        
        <td><%= payment.id %></td>
        <td><%= payment.payment_ref %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.for_cycle.strftime("%m/%Y") %></td>
        <td><%= payment.agent.name %></td>
        <td><%= payment.collected_on %></td>
	    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: "View this payment's details"), payment, class: 'icon', title: "view this payment's details") %></td>
	    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/pen-128.png'), alt: 'Edit this payment'), edit_payment_path(payment), {class: 'icon', title: 'edit this payment'}) if current_user && current_user.has_role?(User::PAYMENTS + User::CAN_DESTROY)%></td>
	    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/trash-128.png'), alt: 'Delete this payment'), payment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon', title:  'delete this payment') if current_user && current_user.has_role?(User::PAYMENTS + User::CAN_DESTROY)%></td>
    <% else %>
    	<td colspan="9">
    <% end %>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/list-128.png'), alt: 'View all payments'), subscriber_payments_path(subscriber), class: 'icon', title: 'view all payments for this subscriber') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/plus-128.png'), alt: 'Add new payment for this subscriber'), new_subscriber_payment_path(subscriber), class: 'icon', title: 'add new payment for this subscriber') %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/show.html.erb
<% unless notice.blank?%>
	<p id="notice"><%= notice %></p> 
<% end %>

<p>
  <b>Payment id:</b>
  <%= @payment.id %>
</p>
<p>
  <b>Payment:</b>
  <%= @payment.payment_ref %>
</p>
<p>
  <b>Subscriber:</b>
  <%= @payment.subscriber_id %>
</p>
<p>
  <b>Subscriber Name:</b>
  <%= @payment.subscriber.name %>
</p>
<p>
  <b>Smartcard Number:</b>
  <%= @payment.subscriber.smartcard_number %>
</p>
<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>
<p>
  <b>For Period:</b>
  <%= @payment.for_cycle.strftime("%m/%Y") %>
</p>
<p>
  <b>Collected By:</b>
  <%= @payment.agent.name %>
</p>
<p>
  <b>Collected On:</b>
  <%= @payment.collected_on %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment), class: 'action edit' %> |
<%= link_to 'List all payments', payments_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || payments_path, class: 'action back' %>