config/routes.rb
Ctvdn::Application.routes.draw do

  resources :channels

  resources :packages

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  
  resources :subscribers do
    resources :payments
    collection do
      get 'inactive'
      get 'active'
    end
  end
  
  resources :payments do
    collection do
      get 'overdues'
    end
  end

  root :to => 'admin#index'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :address, :channels, :cycle_starts_on, :name, :packages, :smartcard_number, :status, :subscription_amount
  has_many :payments
  serialize :packages, Array
  serialize :channels, Array
  
  before_save :correct_data_types
  
  ACTIVE = 1
  INACTIVE = 0
  
  def get_last_payment
    payment = Payment.where(:subscriber_id => self.id).order('id DESC').first
    return payment
  end
  
  def has_package?(package)
    return self.packages.include?(package.id)
  end

  def get_packages
    Package.where(id: self.packages)
  end
  
  def set_packages=(packages=[])
    self.packages = packages.collect(&:id)
  end

  def has_channel?(channel)
    self.channels.include?(channel.id)
  end
  
  def get_channels
    Channel.where(id: self.channels)
  end
  
  def set_channels=(channels=[])
    self.channels = channels.collect(&:id)
  end
  
  def correct_data_types
    self.packages = self.packages.map{|a| a.to_i}
    self.channels = self.channels.map{|a| a.to_i}
  end
  

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  # GET /subscribers
  # GET /subscribers.json
  def index
    @list_name = 'all' 
    
    status = params[:status].to_i if params[:status] == '0' || params[:status] == '1'
    if status.blank?
      @subscribers = Subscriber.paginate(:page  => params[:page], :per_page => 20)
    else
      @list_name += status == Subscriber::ACTIVE ? ' active' : ' inactive'
      @subscribers = Subscriber.where(:status => status).paginate(:page  => params[:page], :per_page => 20)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end

  # GET /subscribers
  # GET /subscribers.json
  def inactive
    @list_name = 'all inactive' 
    @subscribers = Subscriber.where(:status => 0).paginate(:page  => params[:page], :per_page => 20)
    respond_to do |format|
      format.html { render :action => :index}
      format.json { render json: @subscribers }
    end
  end
  # GET /subscribers
  # GET /subscribers.json
  def active
    @list_name = 'all active' 
    @subscribers = Subscriber.where(:status => 1).paginate(:page  => params[:page], :per_page => 20)
    respond_to do |format|
      format.html { render :action => :index}
      format.json { render json: @subscribers }
    end
  end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :smartcard_number %>
    <%= f.text_field :smartcard_number %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cycle_starts_on %>
    <%= f.number_field :cycle_starts_on, in: 1..31 %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address, {:rows => 10} %>
  </div>
  <div class="field">
    <%= f.label :subscription_amount %>
    <%= f.text_field :subscription_amount %>
  </div>
  <div class="field vertical-group">
    <fieldset>
	    <legend>Packages</legend>
	    <%Package.all.each do |package|%>
	        <%= check_box_tag "subscriber[packages][]", package.id, @subscriber.has_package?(package)%>
	        <%= label_tag "subscriber[packages][]", package.name%><br>
	    <%end%>
    </fieldset>
  </div>
  <div class="field vertical-group">
    <fieldset>
    	<legend>Channels</legend>
    	<div>
		    <%Channel.all.each do |channel|%>
		        <%= check_box_tag "subscriber[channels][]", channel.id, @subscriber.has_channel?(channel)%>
		        <%= label_tag "subscriber[channels][]", channel.name%><br>
		    <%end%>
	    </div>
    </fieldset>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber: <%="#{@subscriber.id} (#{@subscriber.name})"%></h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber, class: 'action show' %> |
<%= link_to 'List all subscribers', subscribers_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || subscribers_path, class: 'action back' %>

app/views/subscribers/index.html.erb
<h1>Listing <%= @list_name %> subscribers</h1>

<table>
  <tr class="header">
    <th>Status</th>
    <th>Subscriber Id</th>
    <th>Smartcard number</th>
    <th>Name</th>
    <th>Address</th>
    <th>Cycle starts on (day)</th>
    <th>Package(s)</th>
    <th>À la carte Channel(s)</th>
    <th colspan="5">Tasks</th>
  </tr>

<% @subscribers.each_with_index do |subscriber, i| %>
  <tr class="<%= i%2 == 0 ? '':'alternate'%>">
    <td><%= subscriber.status ? 'Active' : 'Inactive' %></td>
    <td><%= subscriber.id %></td>
    <td><%= subscriber.smartcard_number %></td>
    <td><%= subscriber.name %></td>
    <td><%= subscriber.address %></td>
    <td><%= subscriber.cycle_starts_on %></td>
    <td><%= subscriber.get_packages.collect(&:name).join(',') %></td>
    <td><%= subscriber.get_channels.collect(&:name).join(',') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/eye-128.png'), alt: 'View'), subscriber, class: 'icon', title: 'view') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/pen-128.png'), alt: 'Edit'), edit_subscriber_path(subscriber), {class: 'icon', title: 'edit'}) if current_user && current_user.has_role?(User::SUBSCRIBERS + User::CAN_EDIT)%></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/trash-128.png'), alt: 'Delete'), subscriber, method: :delete, data: { confirm: 'Are you sure?' }, class: 'icon', title:  'delete') if current_user && current_user.has_role?(User::SUBSCRIBERS + User::CAN_DESTROY)%></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/list-128.png'), alt: 'View all payments'), subscriber_payments_path(subscriber), class: 'icon', title: 'view all payments for this subscriber') %></td>
    <td class='action'><%= link_to( image_tag(asset_path('ui-icons/plus-128.png'), alt: 'Add new payment for this subscriber'), new_subscriber_payment_path(subscriber), class: 'icon', title: 'add new payment for this subscriber') %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @subscribers %>
<br />

<%= link_to 'Add new subscriber', new_subscriber_path, class: 'action add-new' %>

app/views/subscribers/new.html.erb
<h1>Add new subscriber</h1>

<%= render 'form' %>

<%= link_to 'Back', request.referer || subscribers_path, class: 'action back'%>

app/views/subscribers/show.html.erb
<% unless notice.blank?%>
	<p id="notice"><%= notice %></p> 
<% end %>
<p>
  <b>Status:</b>
  <%= @subscriber.status ? 'Active' : 'Inactive' %>
</p>

<p>
  <b>Smartcard number:</b>
  <%= @subscriber.smartcard_number %>
</p>

<p>
  <b>Name:</b>
  <%= @subscriber.name %>
</p>

<p>
  <b>Address:</b>
  <%= @subscriber.address %>
</p>

<p>
  <b>Cycle starts on:</b>
  <%= @subscriber.cycle_starts_on %>
</p>

<p>
  <b>Packages:</b>
  <%= @subscriber.get_packages.collect(&:name).join(',') %>
</p>

<p>
  <b>Channels:</b>
  <%= @subscriber.get_channels.collect(&:name).join(',') %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber), class: 'action edit' %> |
<%= link_to 'List all subscribers', subscribers_path, class: 'action list' %> |
<%= link_to 'Back', request.referer || subscribers_path, class: 'action back' %>