config/routes.rb
Ctvdn::Application.routes.draw do

  resources :channels

  resources :packages

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  
  resources :subscribers do
    resources :payments
    collection do
      get 'inactive'
      get 'active'
    end
  end
  
  resources :payments do
    collection do
      get 'overdues'
    end
  end

  root :to => 'admin#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ctvdn</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body class="<%= controller.controller_name %>">
		<div id="banner">
			<%= image_tag("logo.png") %>
			<%= @page_title || t('.title') %>
		</div>
		<div id="columns">
			<div id="side">
				<ul>
					<li><%= link_to 'Home', root_path %></li>
					<li>
						<%= link_to 'Subscribers', subscribers_path %>
						<% if controller.controller_name == 'subscribers'%>
							<ul>
								<li><%= link_to 'Active Subscribers', subscribers_path(status: 1) %></li>
								<li><%= link_to 'Inactive Subscribers', subscribers_path(status: 0) %></li>
								<li><%= link_to 'Add New Subscriber', new_subscriber_path %></li>
							</ul>							
						<%end%>
					</li>
					<li>
						<%= link_to 'Payments', payments_path %>
						<% if controller.controller_name == 'payments'%>
							<ul>
								<li><%= link_to 'Overdue Payments', overdues_payments_path %></li>
								<li><%= link_to 'Add New Payment', new_payment_path %></li>
							</ul>							
						<%end%>
					</li>
					<li>
						<%= link_to 'Users', users_path %>
						<% if controller.controller_name == 'users' && false%>
							<ul>
								<li><%= link_to 'Agents', users_path %></li>	
							</ul>
						<%end%>
					</li>
					
					<li><%= link_to 'Packages', packages_path %></li>
					<li><%= link_to 'Channels', channels_path %></li>
				</ul>
				<% if session[:user_id] %>
					<div class="welcome">Hi <%= current_user.name %>!</div>
					<%= button_to 'Logout', logout_path, method: :delete %>
				<% else %>
					<%= button_to 'Login', login_path, method: :get %>
				<% end %>
			</div>
			<div id="main">
				<% if session[:user_id] %>
					<!-- Hi!! -->
				<% end %>
				<%= yield %>
			</div>
		</div>
	</body>
</html>